### ISSUE TITLE
Spacing in settings UI

### ISSUE THREAD

**Issue by dembeck** [vcprocles/wslcontrol-gui#3]
## ISSUE

Text is being cut off in the UI.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/9568447/216162341-ae592b91-26ea-4a36-a79c-f094ba5131c4.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/9568447/216168720-6bf4fb35-904b-43d7-a7ed-759d8d4ef598.png">

## OTHER

- Also, the contrast makes it difficult to see the text boxes against the background.

**Comment by vcprocles** [comment]
Thanks for the feedback, I didn't really expect someone would find this product of my boredom.

I didn't test the UI against different font sizes and DPIs and the issue seems to be stemming from that (and, frankly, the whole settings UI was sloppily thrown together in the visual editor) 

And I already know about the text boxes. This isn't the only problem with this theme (which i just found on github and thrown in with some small changes), I also don't like how it's hard to distinguish active vs inactive buttons. And this thing throws quite a bit of errors on build. I'm going to look into replacing it or maybe writing my own for the sake of exercise (already created a branch for that).

Thanks again, and sorry in advance if the fix will be slow to make.

**Comment by vcprocles** [comment]
I can't replicate the clipping by changing the scaling from my usual 125% to any other. Do you have a custom font size? 
Anyway, try the latest release with your config. 

Don't close the issue if everything is fixed, as I'm not really finished with visual changes.

P.S. and also I made elements' border more prominent, please tell me if it's easier to see now.

**Comment by vcprocles** [comment]
I tested with different system font sizes. I think there's nothing I can do with my level of knowledge. Even in places where I don't use any static sizes text starts clipping. 

Maybe later if I move to WinUI this will be fixed, but this is unlikely because Windows App SDK is kind of a pain and makes the app much bigger. I have a somewhat-working prototype in a separate branch, though.
